<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>ELK Filesearch</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f2f2f2;
    }

    #search-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    #search-box {
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 8px;
      width: 400px;
      display: flex;
      flex-direction: column;
    }

    #search-input {
      flex: 1;
      padding: 5px;
      border: none;
      outline: none;
    }

    #search-button {
      background-color: #4285f4;
      color: #fff;
      border: none;
      border-radius: 8px;
      padding: 6px 12px;
      cursor: pointer;
      margin-top: 8px;
    }

    #suggestions {
      border: 1px solid #ccc;
      border-radius: 8px;
      margin-top: 8px;
      display: none;
      max-height: 150px;
      overflow-y: auto;
      background-color: #fff;
    }

    .suggestion {
      padding: 8px;
      cursor: pointer;
    }

    .suggestion:hover {
      background-color: #f0f0f0;
    }

    .search-bar {
        background-color: #f2f2f2;
        padding: 10px;
        text-align: center;
    }
  </style>
</head>

<body>
  <div class="search-bar">
    <button class="settings-button" data-toggle="modal" data-target="#urlModal">Ajustes</button>
    
    <button id="search-button" class="search-button">Buscar</button>
  </div>
  <div id="search-container">
    <div id="search-box">
      <input type="text" id="search-input" placeholder="File search">
      <div id="suggestions"></div>
      <button type="button" id="search-button">Buscar <i class="fa fa-search"></i></button>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="urlModal" tabindex="-1" role="dialog" aria-labelledby="urlModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="urlModalLabel">Add URLs</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input type="text" class="form-control mb-2" id="urlInput" placeholder="Enter URL">
          <button type="button" class="btn btn-success" id="addUrlButton">Add URL</button>
          <ul id="urlList" class="list-group mt-3">
            <!-- URLs will be dynamically added here -->
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
    const searchInput = document.getElementById('search-input');
    const suggestionsContainer = document.getElementById('suggestions');
    const searchButton = document.getElementById('search-button');

    searchButton.addEventListener('click', () => {

      window.location.href = "/search/result?q=" + searchInput.value;
    });

    searchInput.addEventListener('input', () => {
      const inputText = searchInput.value.trim();

      if (inputText.length > 0) {
        fetch(`/search/search?q=${inputText}`)
          .then(response => response.json())
          .then(data => {
            const hits = data.hits.hits;
            const suggestions = hits.map(hit => hit._source.title);

            suggestionsContainer.innerHTML = '';
            suggestions.forEach(suggestion => {
              const suggestionElement = document.createElement('div');
              suggestionElement.className = 'suggestion';
              suggestionElement.textContent = suggestion;
              suggestionElement.addEventListener('click', () => {
                searchInput.value = suggestion;
                suggestionsContainer.innerHTML = '';
              });
              suggestionsContainer.appendChild(suggestionElement);
            });

            suggestionsContainer.style.display = 'block';
          })
          .catch(error => {
            console.error('Error fetching data:', error);
          });
      } else {
        suggestionsContainer.innerHTML = '';
        suggestionsContainer.style.display = 'none';
      }
    });

    searchInput.addEventListener('blur', () => {
      setTimeout(() => {
        suggestionsContainer.style.display = 'none';
      }, 200);
    });
  </script>
</body>

</html>